# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CellChangeNotificationTempUeId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mmec': 'str',
        'mtmsi': 'str'
    }

    attribute_map = {
        'mmec': 'mmec',
        'mtmsi': 'mtmsi'
    }

    def __init__(self, mmec=None, mtmsi=None):  # noqa: E501
        """CellChangeNotificationTempUeId - a model defined in Swagger"""  # noqa: E501
        self._mmec = None
        self._mtmsi = None
        self.discriminator = None
        self.mmec = mmec
        self.mtmsi = mtmsi

    @property
    def mmec(self):
        """Gets the mmec of this CellChangeNotificationTempUeId.  # noqa: E501

        MMEC as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The mmec of this CellChangeNotificationTempUeId.  # noqa: E501
        :rtype: str
        """
        return self._mmec

    @mmec.setter
    def mmec(self, mmec):
        """Sets the mmec of this CellChangeNotificationTempUeId.

        MMEC as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param mmec: The mmec of this CellChangeNotificationTempUeId.  # noqa: E501
        :type: str
        """
        if mmec is None:
            raise ValueError("Invalid value for `mmec`, must not be `None`")  # noqa: E501

        self._mmec = mmec

    @property
    def mtmsi(self):
        """Gets the mtmsi of this CellChangeNotificationTempUeId.  # noqa: E501

        M-TMSI as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The mtmsi of this CellChangeNotificationTempUeId.  # noqa: E501
        :rtype: str
        """
        return self._mtmsi

    @mtmsi.setter
    def mtmsi(self, mtmsi):
        """Sets the mtmsi of this CellChangeNotificationTempUeId.

        M-TMSI as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param mtmsi: The mtmsi of this CellChangeNotificationTempUeId.  # noqa: E501
        :type: str
        """
        if mtmsi is None:
            raise ValueError("Invalid value for `mtmsi`, must not be `None`")  # noqa: E501

        self._mtmsi = mtmsi

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CellChangeNotificationTempUeId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CellChangeNotificationTempUeId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
