# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CellChangeNotification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'associate_id': 'list[AssociateId]',
        'ho_status': 'int',
        'notification_type': 'str',
        'src_ecgi': 'Ecgi',
        'temp_ue_id': 'CellChangeNotificationTempUeId',
        'time_stamp': 'TimeStamp',
        'trg_ecgi': 'list[Ecgi]'
    }

    attribute_map = {
        'associate_id': 'associateId',
        'ho_status': 'hoStatus',
        'notification_type': 'notificationType',
        'src_ecgi': 'srcEcgi',
        'temp_ue_id': 'tempUeId',
        'time_stamp': 'timeStamp',
        'trg_ecgi': 'trgEcgi'
    }

    def __init__(self, associate_id=None, ho_status=None, notification_type=None, src_ecgi=None, temp_ue_id=None, time_stamp=None, trg_ecgi=None):  # noqa: E501
        """CellChangeNotification - a model defined in Swagger"""  # noqa: E501
        self._associate_id = None
        self._ho_status = None
        self._notification_type = None
        self._src_ecgi = None
        self._temp_ue_id = None
        self._time_stamp = None
        self._trg_ecgi = None
        self.discriminator = None
        if associate_id is not None:
            self.associate_id = associate_id
        self.ho_status = ho_status
        self.notification_type = notification_type
        self.src_ecgi = src_ecgi
        if temp_ue_id is not None:
            self.temp_ue_id = temp_ue_id
        if time_stamp is not None:
            self.time_stamp = time_stamp
        self.trg_ecgi = trg_ecgi

    @property
    def associate_id(self):
        """Gets the associate_id of this CellChangeNotification.  # noqa: E501

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this CellChangeNotification.  # noqa: E501
        :rtype: list[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id):
        """Sets the associate_id of this CellChangeNotification.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this CellChangeNotification.  # noqa: E501
        :type: list[AssociateId]
        """

        self._associate_id = associate_id

    @property
    def ho_status(self):
        """Gets the ho_status of this CellChangeNotification.  # noqa: E501

        Indicate the status of the UE handover procedure. Values are defined as following: <p>1 = IN_PREPARATION. <p>2 = IN_EXECUTION. <p>3 = COMPLETED. <p>4 = REJECTED. <p>5 = CANCELLED.  # noqa: E501

        :return: The ho_status of this CellChangeNotification.  # noqa: E501
        :rtype: int
        """
        return self._ho_status

    @ho_status.setter
    def ho_status(self, ho_status):
        """Sets the ho_status of this CellChangeNotification.

        Indicate the status of the UE handover procedure. Values are defined as following: <p>1 = IN_PREPARATION. <p>2 = IN_EXECUTION. <p>3 = COMPLETED. <p>4 = REJECTED. <p>5 = CANCELLED.  # noqa: E501

        :param ho_status: The ho_status of this CellChangeNotification.  # noqa: E501
        :type: int
        """
        if ho_status is None:
            raise ValueError("Invalid value for `ho_status`, must not be `None`")  # noqa: E501
        allowed_values = [1, 2, 3, 4, 5]  # noqa: E501
        if ho_status not in allowed_values:
            raise ValueError(
                "Invalid value for `ho_status` ({0}), must be one of {1}"  # noqa: E501
                .format(ho_status, allowed_values)
            )

        self._ho_status = ho_status

    @property
    def notification_type(self):
        """Gets the notification_type of this CellChangeNotification.  # noqa: E501

        Shall be set to \"CellChangeNotification\".  # noqa: E501

        :return: The notification_type of this CellChangeNotification.  # noqa: E501
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type):
        """Sets the notification_type of this CellChangeNotification.

        Shall be set to \"CellChangeNotification\".  # noqa: E501

        :param notification_type: The notification_type of this CellChangeNotification.  # noqa: E501
        :type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def src_ecgi(self):
        """Gets the src_ecgi of this CellChangeNotification.  # noqa: E501


        :return: The src_ecgi of this CellChangeNotification.  # noqa: E501
        :rtype: Ecgi
        """
        return self._src_ecgi

    @src_ecgi.setter
    def src_ecgi(self, src_ecgi):
        """Sets the src_ecgi of this CellChangeNotification.


        :param src_ecgi: The src_ecgi of this CellChangeNotification.  # noqa: E501
        :type: Ecgi
        """
        if src_ecgi is None:
            raise ValueError("Invalid value for `src_ecgi`, must not be `None`")  # noqa: E501

        self._src_ecgi = src_ecgi

    @property
    def temp_ue_id(self):
        """Gets the temp_ue_id of this CellChangeNotification.  # noqa: E501


        :return: The temp_ue_id of this CellChangeNotification.  # noqa: E501
        :rtype: CellChangeNotificationTempUeId
        """
        return self._temp_ue_id

    @temp_ue_id.setter
    def temp_ue_id(self, temp_ue_id):
        """Sets the temp_ue_id of this CellChangeNotification.


        :param temp_ue_id: The temp_ue_id of this CellChangeNotification.  # noqa: E501
        :type: CellChangeNotificationTempUeId
        """

        self._temp_ue_id = temp_ue_id

    @property
    def time_stamp(self):
        """Gets the time_stamp of this CellChangeNotification.  # noqa: E501


        :return: The time_stamp of this CellChangeNotification.  # noqa: E501
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this CellChangeNotification.


        :param time_stamp: The time_stamp of this CellChangeNotification.  # noqa: E501
        :type: TimeStamp
        """

        self._time_stamp = time_stamp

    @property
    def trg_ecgi(self):
        """Gets the trg_ecgi of this CellChangeNotification.  # noqa: E501

        E-UTRAN Cell Global Identifier of the target cell. NOTE: Cardinality N is valid only in case of statuses IN_PREPARATION, REJECTED and CANCELLED.  # noqa: E501

        :return: The trg_ecgi of this CellChangeNotification.  # noqa: E501
        :rtype: list[Ecgi]
        """
        return self._trg_ecgi

    @trg_ecgi.setter
    def trg_ecgi(self, trg_ecgi):
        """Sets the trg_ecgi of this CellChangeNotification.

        E-UTRAN Cell Global Identifier of the target cell. NOTE: Cardinality N is valid only in case of statuses IN_PREPARATION, REJECTED and CANCELLED.  # noqa: E501

        :param trg_ecgi: The trg_ecgi of this CellChangeNotification.  # noqa: E501
        :type: list[Ecgi]
        """
        if trg_ecgi is None:
            raise ValueError("Invalid value for `trg_ecgi`, must not be `None`")  # noqa: E501

        self._trg_ecgi = trg_ecgi

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CellChangeNotification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CellChangeNotification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
