# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class L2Meas(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cell_info': 'list[L2MeasCellInfo]',
        'cell_ue_info': 'list[L2MeasCellUEInfo]',
        'time_stamp': 'TimeStamp'
    }

    attribute_map = {
        'cell_info': 'cellInfo',
        'cell_ue_info': 'cellUEInfo',
        'time_stamp': 'timeStamp'
    }

    def __init__(self, cell_info=None, cell_ue_info=None, time_stamp=None):  # noqa: E501
        """L2Meas - a model defined in Swagger"""  # noqa: E501
        self._cell_info = None
        self._cell_ue_info = None
        self._time_stamp = None
        self.discriminator = None
        if cell_info is not None:
            self.cell_info = cell_info
        if cell_ue_info is not None:
            self.cell_ue_info = cell_ue_info
        if time_stamp is not None:
            self.time_stamp = time_stamp

    @property
    def cell_info(self):
        """Gets the cell_info of this L2Meas.  # noqa: E501

        The per cell measurement information as defined below.  # noqa: E501

        :return: The cell_info of this L2Meas.  # noqa: E501
        :rtype: list[L2MeasCellInfo]
        """
        return self._cell_info

    @cell_info.setter
    def cell_info(self, cell_info):
        """Sets the cell_info of this L2Meas.

        The per cell measurement information as defined below.  # noqa: E501

        :param cell_info: The cell_info of this L2Meas.  # noqa: E501
        :type: list[L2MeasCellInfo]
        """

        self._cell_info = cell_info

    @property
    def cell_ue_info(self):
        """Gets the cell_ue_info of this L2Meas.  # noqa: E501

        The per cell per UE layer 2 measurements information as defined below.  # noqa: E501

        :return: The cell_ue_info of this L2Meas.  # noqa: E501
        :rtype: list[L2MeasCellUEInfo]
        """
        return self._cell_ue_info

    @cell_ue_info.setter
    def cell_ue_info(self, cell_ue_info):
        """Sets the cell_ue_info of this L2Meas.

        The per cell per UE layer 2 measurements information as defined below.  # noqa: E501

        :param cell_ue_info: The cell_ue_info of this L2Meas.  # noqa: E501
        :type: list[L2MeasCellUEInfo]
        """

        self._cell_ue_info = cell_ue_info

    @property
    def time_stamp(self):
        """Gets the time_stamp of this L2Meas.  # noqa: E501


        :return: The time_stamp of this L2Meas.  # noqa: E501
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this L2Meas.


        :param time_stamp: The time_stamp of this L2Meas.  # noqa: E501
        :type: TimeStamp
        """

        self._time_stamp = time_stamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(L2Meas, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, L2Meas):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
