# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class L2MeasCellUEInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'associate_id': 'AssociateId',
        'dl_gbr_data_volume_ue': 'int',
        'dl_gbr_delay_ue': 'int',
        'dl_gbr_pdr_ue': 'int',
        'dl_gbr_throughput_ue': 'int',
        'dl_nongbr_data_volume_ue': 'int',
        'dl_nongbr_delay_ue': 'int',
        'dl_nongbr_pdr_ue': 'int',
        'dl_nongbr_throughput_ue': 'int',
        'ecgi': 'Ecgi',
        'ul_gbr_data_volume_ue': 'int',
        'ul_gbr_delay_ue': 'int',
        'ul_gbr_pdr_ue': 'int',
        'ul_gbr_throughput_ue': 'int',
        'ul_nongbr_data_volume_ue': 'int',
        'ul_nongbr_delay_ue': 'int',
        'ul_nongbr_pdr_ue': 'int',
        'ul_nongbr_throughput_ue': 'int'
    }

    attribute_map = {
        'associate_id': 'associateId',
        'dl_gbr_data_volume_ue': 'dl_gbr_data_volume_ue',
        'dl_gbr_delay_ue': 'dl_gbr_delay_ue',
        'dl_gbr_pdr_ue': 'dl_gbr_pdr_ue',
        'dl_gbr_throughput_ue': 'dl_gbr_throughput_ue',
        'dl_nongbr_data_volume_ue': 'dl_nongbr_data_volume_ue',
        'dl_nongbr_delay_ue': 'dl_nongbr_delay_ue',
        'dl_nongbr_pdr_ue': 'dl_nongbr_pdr_ue',
        'dl_nongbr_throughput_ue': 'dl_nongbr_throughput_ue',
        'ecgi': 'ecgi',
        'ul_gbr_data_volume_ue': 'ul_gbr_data_volume_ue',
        'ul_gbr_delay_ue': 'ul_gbr_delay_ue',
        'ul_gbr_pdr_ue': 'ul_gbr_pdr_ue',
        'ul_gbr_throughput_ue': 'ul_gbr_throughput_ue',
        'ul_nongbr_data_volume_ue': 'ul_nongbr_data_volume_ue',
        'ul_nongbr_delay_ue': 'ul_nongbr_delay_ue',
        'ul_nongbr_pdr_ue': 'ul_nongbr_pdr_ue',
        'ul_nongbr_throughput_ue': 'ul_nongbr_throughput_ue'
    }

    def __init__(self, associate_id=None, dl_gbr_data_volume_ue=None, dl_gbr_delay_ue=None, dl_gbr_pdr_ue=None, dl_gbr_throughput_ue=None, dl_nongbr_data_volume_ue=None, dl_nongbr_delay_ue=None, dl_nongbr_pdr_ue=None, dl_nongbr_throughput_ue=None, ecgi=None, ul_gbr_data_volume_ue=None, ul_gbr_delay_ue=None, ul_gbr_pdr_ue=None, ul_gbr_throughput_ue=None, ul_nongbr_data_volume_ue=None, ul_nongbr_delay_ue=None, ul_nongbr_pdr_ue=None, ul_nongbr_throughput_ue=None):  # noqa: E501
        """L2MeasCellUEInfo - a model defined in Swagger"""  # noqa: E501
        self._associate_id = None
        self._dl_gbr_data_volume_ue = None
        self._dl_gbr_delay_ue = None
        self._dl_gbr_pdr_ue = None
        self._dl_gbr_throughput_ue = None
        self._dl_nongbr_data_volume_ue = None
        self._dl_nongbr_delay_ue = None
        self._dl_nongbr_pdr_ue = None
        self._dl_nongbr_throughput_ue = None
        self._ecgi = None
        self._ul_gbr_data_volume_ue = None
        self._ul_gbr_delay_ue = None
        self._ul_gbr_pdr_ue = None
        self._ul_gbr_throughput_ue = None
        self._ul_nongbr_data_volume_ue = None
        self._ul_nongbr_delay_ue = None
        self._ul_nongbr_pdr_ue = None
        self._ul_nongbr_throughput_ue = None
        self.discriminator = None
        if associate_id is not None:
            self.associate_id = associate_id
        if dl_gbr_data_volume_ue is not None:
            self.dl_gbr_data_volume_ue = dl_gbr_data_volume_ue
        if dl_gbr_delay_ue is not None:
            self.dl_gbr_delay_ue = dl_gbr_delay_ue
        if dl_gbr_pdr_ue is not None:
            self.dl_gbr_pdr_ue = dl_gbr_pdr_ue
        if dl_gbr_throughput_ue is not None:
            self.dl_gbr_throughput_ue = dl_gbr_throughput_ue
        if dl_nongbr_data_volume_ue is not None:
            self.dl_nongbr_data_volume_ue = dl_nongbr_data_volume_ue
        if dl_nongbr_delay_ue is not None:
            self.dl_nongbr_delay_ue = dl_nongbr_delay_ue
        if dl_nongbr_pdr_ue is not None:
            self.dl_nongbr_pdr_ue = dl_nongbr_pdr_ue
        if dl_nongbr_throughput_ue is not None:
            self.dl_nongbr_throughput_ue = dl_nongbr_throughput_ue
        if ecgi is not None:
            self.ecgi = ecgi
        if ul_gbr_data_volume_ue is not None:
            self.ul_gbr_data_volume_ue = ul_gbr_data_volume_ue
        if ul_gbr_delay_ue is not None:
            self.ul_gbr_delay_ue = ul_gbr_delay_ue
        if ul_gbr_pdr_ue is not None:
            self.ul_gbr_pdr_ue = ul_gbr_pdr_ue
        if ul_gbr_throughput_ue is not None:
            self.ul_gbr_throughput_ue = ul_gbr_throughput_ue
        if ul_nongbr_data_volume_ue is not None:
            self.ul_nongbr_data_volume_ue = ul_nongbr_data_volume_ue
        if ul_nongbr_delay_ue is not None:
            self.ul_nongbr_delay_ue = ul_nongbr_delay_ue
        if ul_nongbr_pdr_ue is not None:
            self.ul_nongbr_pdr_ue = ul_nongbr_pdr_ue
        if ul_nongbr_throughput_ue is not None:
            self.ul_nongbr_throughput_ue = ul_nongbr_throughput_ue

    @property
    def associate_id(self):
        """Gets the associate_id of this L2MeasCellUEInfo.  # noqa: E501


        :return: The associate_id of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: AssociateId
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id):
        """Sets the associate_id of this L2MeasCellUEInfo.


        :param associate_id: The associate_id of this L2MeasCellUEInfo.  # noqa: E501
        :type: AssociateId
        """

        self._associate_id = associate_id

    @property
    def dl_gbr_data_volume_ue(self):
        """Gets the dl_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the data volume of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_gbr_data_volume_ue

    @dl_gbr_data_volume_ue.setter
    def dl_gbr_data_volume_ue(self, dl_gbr_data_volume_ue):
        """Sets the dl_gbr_data_volume_ue of this L2MeasCellUEInfo.

        It indicates the data volume of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_gbr_data_volume_ue: The dl_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_gbr_data_volume_ue = dl_gbr_data_volume_ue

    @property
    def dl_gbr_delay_ue(self):
        """Gets the dl_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet delay of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_gbr_delay_ue

    @dl_gbr_delay_ue.setter
    def dl_gbr_delay_ue(self, dl_gbr_delay_ue):
        """Sets the dl_gbr_delay_ue of this L2MeasCellUEInfo.

        It indicates the packet delay of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_gbr_delay_ue: The dl_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_gbr_delay_ue = dl_gbr_delay_ue

    @property
    def dl_gbr_pdr_ue(self):
        """Gets the dl_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet discard rate in percentage of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_gbr_pdr_ue

    @dl_gbr_pdr_ue.setter
    def dl_gbr_pdr_ue(self, dl_gbr_pdr_ue):
        """Sets the dl_gbr_pdr_ue of this L2MeasCellUEInfo.

        It indicates the packet discard rate in percentage of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_gbr_pdr_ue: The dl_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_gbr_pdr_ue = dl_gbr_pdr_ue

    @property
    def dl_gbr_throughput_ue(self):
        """Gets the dl_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the scheduled throughput of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_gbr_throughput_ue

    @dl_gbr_throughput_ue.setter
    def dl_gbr_throughput_ue(self, dl_gbr_throughput_ue):
        """Sets the dl_gbr_throughput_ue of this L2MeasCellUEInfo.

        It indicates the scheduled throughput of the downlink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_gbr_throughput_ue: The dl_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_gbr_throughput_ue = dl_gbr_throughput_ue

    @property
    def dl_nongbr_data_volume_ue(self):
        """Gets the dl_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the data volume of the downlink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_nongbr_data_volume_ue

    @dl_nongbr_data_volume_ue.setter
    def dl_nongbr_data_volume_ue(self, dl_nongbr_data_volume_ue):
        """Sets the dl_nongbr_data_volume_ue of this L2MeasCellUEInfo.

        It indicates the data volume of the downlink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_nongbr_data_volume_ue: The dl_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_nongbr_data_volume_ue = dl_nongbr_data_volume_ue

    @property
    def dl_nongbr_delay_ue(self):
        """Gets the dl_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet delay of the downlink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_nongbr_delay_ue

    @dl_nongbr_delay_ue.setter
    def dl_nongbr_delay_ue(self, dl_nongbr_delay_ue):
        """Sets the dl_nongbr_delay_ue of this L2MeasCellUEInfo.

        It indicates the packet delay of the downlink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_nongbr_delay_ue: The dl_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_nongbr_delay_ue = dl_nongbr_delay_ue

    @property
    def dl_nongbr_pdr_ue(self):
        """Gets the dl_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet discard rate in percentage of the downlink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_nongbr_pdr_ue

    @dl_nongbr_pdr_ue.setter
    def dl_nongbr_pdr_ue(self, dl_nongbr_pdr_ue):
        """Sets the dl_nongbr_pdr_ue of this L2MeasCellUEInfo.

        It indicates the packet discard rate in percentage of the downlink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_nongbr_pdr_ue: The dl_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_nongbr_pdr_ue = dl_nongbr_pdr_ue

    @property
    def dl_nongbr_throughput_ue(self):
        """Gets the dl_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the scheduled throughput of the downlink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The dl_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._dl_nongbr_throughput_ue

    @dl_nongbr_throughput_ue.setter
    def dl_nongbr_throughput_ue(self, dl_nongbr_throughput_ue):
        """Sets the dl_nongbr_throughput_ue of this L2MeasCellUEInfo.

        It indicates the scheduled throughput of the downlink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param dl_nongbr_throughput_ue: The dl_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._dl_nongbr_throughput_ue = dl_nongbr_throughput_ue

    @property
    def ecgi(self):
        """Gets the ecgi of this L2MeasCellUEInfo.  # noqa: E501


        :return: The ecgi of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi):
        """Sets the ecgi of this L2MeasCellUEInfo.


        :param ecgi: The ecgi of this L2MeasCellUEInfo.  # noqa: E501
        :type: Ecgi
        """

        self._ecgi = ecgi

    @property
    def ul_gbr_data_volume_ue(self):
        """Gets the ul_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the data volume of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_gbr_data_volume_ue

    @ul_gbr_data_volume_ue.setter
    def ul_gbr_data_volume_ue(self, ul_gbr_data_volume_ue):
        """Sets the ul_gbr_data_volume_ue of this L2MeasCellUEInfo.

        It indicates the data volume of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_gbr_data_volume_ue: The ul_gbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_gbr_data_volume_ue = ul_gbr_data_volume_ue

    @property
    def ul_gbr_delay_ue(self):
        """Gets the ul_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet delay of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_gbr_delay_ue

    @ul_gbr_delay_ue.setter
    def ul_gbr_delay_ue(self, ul_gbr_delay_ue):
        """Sets the ul_gbr_delay_ue of this L2MeasCellUEInfo.

        It indicates the packet delay of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_gbr_delay_ue: The ul_gbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_gbr_delay_ue = ul_gbr_delay_ue

    @property
    def ul_gbr_pdr_ue(self):
        """Gets the ul_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet discard rate in percentage of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_gbr_pdr_ue

    @ul_gbr_pdr_ue.setter
    def ul_gbr_pdr_ue(self, ul_gbr_pdr_ue):
        """Sets the ul_gbr_pdr_ue of this L2MeasCellUEInfo.

        It indicates the packet discard rate in percentage of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_gbr_pdr_ue: The ul_gbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_gbr_pdr_ue = ul_gbr_pdr_ue

    @property
    def ul_gbr_throughput_ue(self):
        """Gets the ul_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the scheduled throughput of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_gbr_throughput_ue

    @ul_gbr_throughput_ue.setter
    def ul_gbr_throughput_ue(self, ul_gbr_throughput_ue):
        """Sets the ul_gbr_throughput_ue of this L2MeasCellUEInfo.

        It indicates the scheduled throughput of the uplink GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_gbr_throughput_ue: The ul_gbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_gbr_throughput_ue = ul_gbr_throughput_ue

    @property
    def ul_nongbr_data_volume_ue(self):
        """Gets the ul_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the data volume of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_nongbr_data_volume_ue

    @ul_nongbr_data_volume_ue.setter
    def ul_nongbr_data_volume_ue(self, ul_nongbr_data_volume_ue):
        """Sets the ul_nongbr_data_volume_ue of this L2MeasCellUEInfo.

        It indicates the data volume of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_nongbr_data_volume_ue: The ul_nongbr_data_volume_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_nongbr_data_volume_ue = ul_nongbr_data_volume_ue

    @property
    def ul_nongbr_delay_ue(self):
        """Gets the ul_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet delay of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_nongbr_delay_ue

    @ul_nongbr_delay_ue.setter
    def ul_nongbr_delay_ue(self, ul_nongbr_delay_ue):
        """Sets the ul_nongbr_delay_ue of this L2MeasCellUEInfo.

        It indicates the packet delay of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_nongbr_delay_ue: The ul_nongbr_delay_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_nongbr_delay_ue = ul_nongbr_delay_ue

    @property
    def ul_nongbr_pdr_ue(self):
        """Gets the ul_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the packet discard rate in percentage of the uplink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_nongbr_pdr_ue

    @ul_nongbr_pdr_ue.setter
    def ul_nongbr_pdr_ue(self, ul_nongbr_pdr_ue):
        """Sets the ul_nongbr_pdr_ue of this L2MeasCellUEInfo.

        It indicates the packet discard rate in percentage of the uplink nonGBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_nongbr_pdr_ue: The ul_nongbr_pdr_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_nongbr_pdr_ue = ul_nongbr_pdr_ue

    @property
    def ul_nongbr_throughput_ue(self):
        """Gets the ul_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501

        It indicates the scheduled throughput of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :return: The ul_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :rtype: int
        """
        return self._ul_nongbr_throughput_ue

    @ul_nongbr_throughput_ue.setter
    def ul_nongbr_throughput_ue(self, ul_nongbr_throughput_ue):
        """Sets the ul_nongbr_throughput_ue of this L2MeasCellUEInfo.

        It indicates the scheduled throughput of the uplink non-GBR traffic of a UE, as defined in ETSI TS 136 314 [i.11].  # noqa: E501

        :param ul_nongbr_throughput_ue: The ul_nongbr_throughput_ue of this L2MeasCellUEInfo.  # noqa: E501
        :type: int
        """

        self._ul_nongbr_throughput_ue = ul_nongbr_throughput_ue

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(L2MeasCellUEInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, L2MeasCellUEInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
