# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeasRepUeNotificationNrBNCsNrBNCellInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nr_bn_cell_g_id': 'NrCellId',
        'nr_bn_cell_plmn': 'list[Plmn]'
    }

    attribute_map = {
        'nr_bn_cell_g_id': 'nrBNCellGId',
        'nr_bn_cell_plmn': 'nrBNCellPlmn'
    }

    def __init__(self, nr_bn_cell_g_id=None, nr_bn_cell_plmn=None):  # noqa: E501
        """MeasRepUeNotificationNrBNCsNrBNCellInfo - a model defined in Swagger"""  # noqa: E501
        self._nr_bn_cell_g_id = None
        self._nr_bn_cell_plmn = None
        self.discriminator = None
        if nr_bn_cell_g_id is not None:
            self.nr_bn_cell_g_id = nr_bn_cell_g_id
        if nr_bn_cell_plmn is not None:
            self.nr_bn_cell_plmn = nr_bn_cell_plmn

    @property
    def nr_bn_cell_g_id(self):
        """Gets the nr_bn_cell_g_id of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501


        :return: The nr_bn_cell_g_id of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501
        :rtype: NrCellId
        """
        return self._nr_bn_cell_g_id

    @nr_bn_cell_g_id.setter
    def nr_bn_cell_g_id(self, nr_bn_cell_g_id):
        """Sets the nr_bn_cell_g_id of this MeasRepUeNotificationNrBNCsNrBNCellInfo.


        :param nr_bn_cell_g_id: The nr_bn_cell_g_id of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501
        :type: NrCellId
        """

        self._nr_bn_cell_g_id = nr_bn_cell_g_id

    @property
    def nr_bn_cell_plmn(self):
        """Gets the nr_bn_cell_plmn of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501

        Public land mobile network identities  # noqa: E501

        :return: The nr_bn_cell_plmn of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501
        :rtype: list[Plmn]
        """
        return self._nr_bn_cell_plmn

    @nr_bn_cell_plmn.setter
    def nr_bn_cell_plmn(self, nr_bn_cell_plmn):
        """Sets the nr_bn_cell_plmn of this MeasRepUeNotificationNrBNCsNrBNCellInfo.

        Public land mobile network identities  # noqa: E501

        :param nr_bn_cell_plmn: The nr_bn_cell_plmn of this MeasRepUeNotificationNrBNCsNrBNCellInfo.  # noqa: E501
        :type: list[Plmn]
        """

        self._nr_bn_cell_plmn = nr_bn_cell_plmn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeasRepUeNotificationNrBNCsNrBNCellInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeasRepUeNotificationNrBNCsNrBNCellInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
