# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NrMeasRepUeNotificationSCell(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meas_quantity_results_csi_rs_cell': 'MeasQuantityResultsNr',
        'meas_quantity_results_ssb_cell': 'MeasQuantityResultsNr',
        'rs_index_results': 'RsIndexResults'
    }

    attribute_map = {
        'meas_quantity_results_csi_rs_cell': 'measQuantityResultsCsiRsCell',
        'meas_quantity_results_ssb_cell': 'measQuantityResultsSsbCell',
        'rs_index_results': 'rsIndexResults'
    }

    def __init__(self, meas_quantity_results_csi_rs_cell=None, meas_quantity_results_ssb_cell=None, rs_index_results=None):  # noqa: E501
        """NrMeasRepUeNotificationSCell - a model defined in Swagger"""  # noqa: E501
        self._meas_quantity_results_csi_rs_cell = None
        self._meas_quantity_results_ssb_cell = None
        self._rs_index_results = None
        self.discriminator = None
        if meas_quantity_results_csi_rs_cell is not None:
            self.meas_quantity_results_csi_rs_cell = meas_quantity_results_csi_rs_cell
        if meas_quantity_results_ssb_cell is not None:
            self.meas_quantity_results_ssb_cell = meas_quantity_results_ssb_cell
        if rs_index_results is not None:
            self.rs_index_results = rs_index_results

    @property
    def meas_quantity_results_csi_rs_cell(self):
        """Gets the meas_quantity_results_csi_rs_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501


        :return: The meas_quantity_results_csi_rs_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :rtype: MeasQuantityResultsNr
        """
        return self._meas_quantity_results_csi_rs_cell

    @meas_quantity_results_csi_rs_cell.setter
    def meas_quantity_results_csi_rs_cell(self, meas_quantity_results_csi_rs_cell):
        """Sets the meas_quantity_results_csi_rs_cell of this NrMeasRepUeNotificationSCell.


        :param meas_quantity_results_csi_rs_cell: The meas_quantity_results_csi_rs_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :type: MeasQuantityResultsNr
        """

        self._meas_quantity_results_csi_rs_cell = meas_quantity_results_csi_rs_cell

    @property
    def meas_quantity_results_ssb_cell(self):
        """Gets the meas_quantity_results_ssb_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501


        :return: The meas_quantity_results_ssb_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :rtype: MeasQuantityResultsNr
        """
        return self._meas_quantity_results_ssb_cell

    @meas_quantity_results_ssb_cell.setter
    def meas_quantity_results_ssb_cell(self, meas_quantity_results_ssb_cell):
        """Sets the meas_quantity_results_ssb_cell of this NrMeasRepUeNotificationSCell.


        :param meas_quantity_results_ssb_cell: The meas_quantity_results_ssb_cell of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :type: MeasQuantityResultsNr
        """

        self._meas_quantity_results_ssb_cell = meas_quantity_results_ssb_cell

    @property
    def rs_index_results(self):
        """Gets the rs_index_results of this NrMeasRepUeNotificationSCell.  # noqa: E501


        :return: The rs_index_results of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :rtype: RsIndexResults
        """
        return self._rs_index_results

    @rs_index_results.setter
    def rs_index_results(self, rs_index_results):
        """Sets the rs_index_results of this NrMeasRepUeNotificationSCell.


        :param rs_index_results: The rs_index_results of this NrMeasRepUeNotificationSCell.  # noqa: E501
        :type: RsIndexResults
        """

        self._rs_index_results = rs_index_results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NrMeasRepUeNotificationSCell, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NrMeasRepUeNotificationSCell):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
