# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NrMeasRepUeNotificationServCellMeasInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'n_cell': 'NrMeasRepUeNotificationNCell',
        'nrcgi': 'NRcgi',
        's_cell': 'NrMeasRepUeNotificationSCell'
    }

    attribute_map = {
        'n_cell': 'nCell',
        'nrcgi': 'nrcgi',
        's_cell': 'sCell'
    }

    def __init__(self, n_cell=None, nrcgi=None, s_cell=None):  # noqa: E501
        """NrMeasRepUeNotificationServCellMeasInfo - a model defined in Swagger"""  # noqa: E501
        self._n_cell = None
        self._nrcgi = None
        self._s_cell = None
        self.discriminator = None
        if n_cell is not None:
            self.n_cell = n_cell
        if nrcgi is not None:
            self.nrcgi = nrcgi
        if s_cell is not None:
            self.s_cell = s_cell

    @property
    def n_cell(self):
        """Gets the n_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501


        :return: The n_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :rtype: NrMeasRepUeNotificationNCell
        """
        return self._n_cell

    @n_cell.setter
    def n_cell(self, n_cell):
        """Sets the n_cell of this NrMeasRepUeNotificationServCellMeasInfo.


        :param n_cell: The n_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :type: NrMeasRepUeNotificationNCell
        """

        self._n_cell = n_cell

    @property
    def nrcgi(self):
        """Gets the nrcgi of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501


        :return: The nrcgi of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :rtype: NRcgi
        """
        return self._nrcgi

    @nrcgi.setter
    def nrcgi(self, nrcgi):
        """Sets the nrcgi of this NrMeasRepUeNotificationServCellMeasInfo.


        :param nrcgi: The nrcgi of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :type: NRcgi
        """

        self._nrcgi = nrcgi

    @property
    def s_cell(self):
        """Gets the s_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501


        :return: The s_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :rtype: NrMeasRepUeNotificationSCell
        """
        return self._s_cell

    @s_cell.setter
    def s_cell(self, s_cell):
        """Sets the s_cell of this NrMeasRepUeNotificationServCellMeasInfo.


        :param s_cell: The s_cell of this NrMeasRepUeNotificationServCellMeasInfo.  # noqa: E501
        :type: NrMeasRepUeNotificationSCell
        """

        self._s_cell = s_cell

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NrMeasRepUeNotificationServCellMeasInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NrMeasRepUeNotificationServCellMeasInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
