# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RabInfoUeInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'associate_id': 'list[AssociateId]',
        'erab_info': 'list[RabInfoErabInfo]'
    }

    attribute_map = {
        'associate_id': 'associateId',
        'erab_info': 'erabInfo'
    }

    def __init__(self, associate_id=None, erab_info=None):  # noqa: E501
        """RabInfoUeInfo - a model defined in Swagger"""  # noqa: E501
        self._associate_id = None
        self._erab_info = None
        self.discriminator = None
        if associate_id is not None:
            self.associate_id = associate_id
        if erab_info is not None:
            self.erab_info = erab_info

    @property
    def associate_id(self):
        """Gets the associate_id of this RabInfoUeInfo.  # noqa: E501

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :return: The associate_id of this RabInfoUeInfo.  # noqa: E501
        :rtype: list[AssociateId]
        """
        return self._associate_id

    @associate_id.setter
    def associate_id(self, associate_id):
        """Sets the associate_id of this RabInfoUeInfo.

        0 to N identifiers to associate the event for a specific UE or flow.  # noqa: E501

        :param associate_id: The associate_id of this RabInfoUeInfo.  # noqa: E501
        :type: list[AssociateId]
        """

        self._associate_id = associate_id

    @property
    def erab_info(self):
        """Gets the erab_info of this RabInfoUeInfo.  # noqa: E501

        Information on E-RAB as defined below.  # noqa: E501

        :return: The erab_info of this RabInfoUeInfo.  # noqa: E501
        :rtype: list[RabInfoErabInfo]
        """
        return self._erab_info

    @erab_info.setter
    def erab_info(self, erab_info):
        """Sets the erab_info of this RabInfoUeInfo.

        Information on E-RAB as defined below.  # noqa: E501

        :param erab_info: The erab_info of this RabInfoUeInfo.  # noqa: E501
        :type: list[RabInfoErabInfo]
        """

        self._erab_info = erab_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RabInfoUeInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RabInfoUeInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
