# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RabModNotificationErabQosParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qci': 'int',
        'qos_information': 'RabModNotificationErabQosParametersQosInformation'
    }

    attribute_map = {
        'qci': 'qci',
        'qos_information': 'qosInformation'
    }

    def __init__(self, qci=None, qos_information=None):  # noqa: E501
        """RabModNotificationErabQosParameters - a model defined in Swagger"""  # noqa: E501
        self._qci = None
        self._qos_information = None
        self.discriminator = None
        self.qci = qci
        if qos_information is not None:
            self.qos_information = qos_information

    @property
    def qci(self):
        """Gets the qci of this RabModNotificationErabQosParameters.  # noqa: E501

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :return: The qci of this RabModNotificationErabQosParameters.  # noqa: E501
        :rtype: int
        """
        return self._qci

    @qci.setter
    def qci(self, qci):
        """Sets the qci of this RabModNotificationErabQosParameters.

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :param qci: The qci of this RabModNotificationErabQosParameters.  # noqa: E501
        :type: int
        """
        if qci is None:
            raise ValueError("Invalid value for `qci`, must not be `None`")  # noqa: E501

        self._qci = qci

    @property
    def qos_information(self):
        """Gets the qos_information of this RabModNotificationErabQosParameters.  # noqa: E501


        :return: The qos_information of this RabModNotificationErabQosParameters.  # noqa: E501
        :rtype: RabModNotificationErabQosParametersQosInformation
        """
        return self._qos_information

    @qos_information.setter
    def qos_information(self, qos_information):
        """Sets the qos_information of this RabModNotificationErabQosParameters.


        :param qos_information: The qos_information of this RabModNotificationErabQosParameters.  # noqa: E501
        :type: RabModNotificationErabQosParametersQosInformation
        """

        self._qos_information = qos_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RabModNotificationErabQosParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RabModNotificationErabQosParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
