# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RabInfoCellUserInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ecgi': 'Ecgi',
        'ue_info': 'list[RabInfoUeInfo]'
    }

    attribute_map = {
        'ecgi': 'ecgi',
        'ue_info': 'ueInfo'
    }

    def __init__(self, ecgi=None, ue_info=None):  # noqa: E501
        """RabInfoCellUserInfo - a model defined in Swagger"""  # noqa: E501
        self._ecgi = None
        self._ue_info = None
        self.discriminator = None
        if ecgi is not None:
            self.ecgi = ecgi
        if ue_info is not None:
            self.ue_info = ue_info

    @property
    def ecgi(self):
        """Gets the ecgi of this RabInfoCellUserInfo.  # noqa: E501


        :return: The ecgi of this RabInfoCellUserInfo.  # noqa: E501
        :rtype: Ecgi
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi):
        """Sets the ecgi of this RabInfoCellUserInfo.


        :param ecgi: The ecgi of this RabInfoCellUserInfo.  # noqa: E501
        :type: Ecgi
        """

        self._ecgi = ecgi

    @property
    def ue_info(self):
        """Gets the ue_info of this RabInfoCellUserInfo.  # noqa: E501

        Information on UEs in the specific cell as defined below.  # noqa: E501

        :return: The ue_info of this RabInfoCellUserInfo.  # noqa: E501
        :rtype: list[RabInfoUeInfo]
        """
        return self._ue_info

    @ue_info.setter
    def ue_info(self, ue_info):
        """Sets the ue_info of this RabInfoCellUserInfo.

        Information on UEs in the specific cell as defined below.  # noqa: E501

        :param ue_info: The ue_info of this RabInfoCellUserInfo.  # noqa: E501
        :type: list[RabInfoUeInfo]
        """

        self._ue_info = ue_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RabInfoCellUserInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RabInfoCellUserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
