# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RabModSubscriptionFilterCriteriaQci(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_instance_id': 'str',
        'ecgi': 'list[Ecgi]',
        'erab_id': 'int',
        'qci': 'int'
    }

    attribute_map = {
        'app_instance_id': 'appInstanceId',
        'ecgi': 'ecgi',
        'erab_id': 'erabId',
        'qci': 'qci'
    }

    def __init__(self, app_instance_id=None, ecgi=None, erab_id=None, qci=None):  # noqa: E501
        """RabModSubscriptionFilterCriteriaQci - a model defined in Swagger"""  # noqa: E501
        self._app_instance_id = None
        self._ecgi = None
        self._erab_id = None
        self._qci = None
        self.discriminator = None
        if app_instance_id is not None:
            self.app_instance_id = app_instance_id
        if ecgi is not None:
            self.ecgi = ecgi
        self.erab_id = erab_id
        self.qci = qci

    @property
    def app_instance_id(self):
        """Gets the app_instance_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501

        Unique identifier for the MEC application instance.  # noqa: E501

        :return: The app_instance_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :rtype: str
        """
        return self._app_instance_id

    @app_instance_id.setter
    def app_instance_id(self, app_instance_id):
        """Sets the app_instance_id of this RabModSubscriptionFilterCriteriaQci.

        Unique identifier for the MEC application instance.  # noqa: E501

        :param app_instance_id: The app_instance_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :type: str
        """

        self._app_instance_id = app_instance_id

    @property
    def ecgi(self):
        """Gets the ecgi of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :return: The ecgi of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :rtype: list[Ecgi]
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi):
        """Sets the ecgi of this RabModSubscriptionFilterCriteriaQci.

        E-UTRAN Cell Global Identifier.  # noqa: E501

        :param ecgi: The ecgi of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :type: list[Ecgi]
        """

        self._ecgi = ecgi

    @property
    def erab_id(self):
        """Gets the erab_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id):
        """Sets the erab_id of this RabModSubscriptionFilterCriteriaQci.

        The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :type: int
        """
        if erab_id is None:
            raise ValueError("Invalid value for `erab_id`, must not be `None`")  # noqa: E501

        self._erab_id = erab_id

    @property
    def qci(self):
        """Gets the qci of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :return: The qci of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :rtype: int
        """
        return self._qci

    @qci.setter
    def qci(self, qci):
        """Sets the qci of this RabModSubscriptionFilterCriteriaQci.

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :param qci: The qci of this RabModSubscriptionFilterCriteriaQci.  # noqa: E501
        :type: int
        """
        if qci is None:
            raise ValueError("Invalid value for `qci`, must not be `None`")  # noqa: E501

        self._qci = qci

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RabModSubscriptionFilterCriteriaQci, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RabModSubscriptionFilterCriteriaQci):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
