# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class S1BearerSubscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        's1_bearer_subscription_criteria': 'S1BearerSubscriptionS1BearerSubscriptionCriteria',
        'links': 'CaReconfSubscriptionLinks',
        'callback_reference': 'str',
        'event_type': 'list[Enum]',
        'expiry_deadline': 'TimeStamp',
        'subscription_type': 'str'
    }

    attribute_map = {
        's1_bearer_subscription_criteria': 'S1BearerSubscriptionCriteria',
        'links': '_links',
        'callback_reference': 'callbackReference',
        'event_type': 'eventType',
        'expiry_deadline': 'expiryDeadline',
        'subscription_type': 'subscriptionType'
    }

    def __init__(self, s1_bearer_subscription_criteria=None, links=None, callback_reference=None, event_type=None, expiry_deadline=None, subscription_type=None):  # noqa: E501
        """S1BearerSubscription - a model defined in Swagger"""  # noqa: E501
        self._s1_bearer_subscription_criteria = None
        self._links = None
        self._callback_reference = None
        self._event_type = None
        self._expiry_deadline = None
        self._subscription_type = None
        self.discriminator = None
        self.s1_bearer_subscription_criteria = s1_bearer_subscription_criteria
        if links is not None:
            self.links = links
        self.callback_reference = callback_reference
        self.event_type = event_type
        if expiry_deadline is not None:
            self.expiry_deadline = expiry_deadline
        self.subscription_type = subscription_type

    @property
    def s1_bearer_subscription_criteria(self):
        """Gets the s1_bearer_subscription_criteria of this S1BearerSubscription.  # noqa: E501


        :return: The s1_bearer_subscription_criteria of this S1BearerSubscription.  # noqa: E501
        :rtype: S1BearerSubscriptionS1BearerSubscriptionCriteria
        """
        return self._s1_bearer_subscription_criteria

    @s1_bearer_subscription_criteria.setter
    def s1_bearer_subscription_criteria(self, s1_bearer_subscription_criteria):
        """Sets the s1_bearer_subscription_criteria of this S1BearerSubscription.


        :param s1_bearer_subscription_criteria: The s1_bearer_subscription_criteria of this S1BearerSubscription.  # noqa: E501
        :type: S1BearerSubscriptionS1BearerSubscriptionCriteria
        """
        if s1_bearer_subscription_criteria is None:
            raise ValueError("Invalid value for `s1_bearer_subscription_criteria`, must not be `None`")  # noqa: E501

        self._s1_bearer_subscription_criteria = s1_bearer_subscription_criteria

    @property
    def links(self):
        """Gets the links of this S1BearerSubscription.  # noqa: E501


        :return: The links of this S1BearerSubscription.  # noqa: E501
        :rtype: CaReconfSubscriptionLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this S1BearerSubscription.


        :param links: The links of this S1BearerSubscription.  # noqa: E501
        :type: CaReconfSubscriptionLinks
        """

        self._links = links

    @property
    def callback_reference(self):
        """Gets the callback_reference of this S1BearerSubscription.  # noqa: E501

        URI selected by the service consumer, to receive notifications on the subscribed RNIS information. This shall be included in the request and response.  # noqa: E501

        :return: The callback_reference of this S1BearerSubscription.  # noqa: E501
        :rtype: str
        """
        return self._callback_reference

    @callback_reference.setter
    def callback_reference(self, callback_reference):
        """Sets the callback_reference of this S1BearerSubscription.

        URI selected by the service consumer, to receive notifications on the subscribed RNIS information. This shall be included in the request and response.  # noqa: E501

        :param callback_reference: The callback_reference of this S1BearerSubscription.  # noqa: E501
        :type: str
        """
        if callback_reference is None:
            raise ValueError("Invalid value for `callback_reference`, must not be `None`")  # noqa: E501

        self._callback_reference = callback_reference

    @property
    def event_type(self):
        """Gets the event_type of this S1BearerSubscription.  # noqa: E501

        Description of the subscribed event. The event is included both in the request and in the response. \\nFor the eventType, the following values are currently defined: <p>0 = RESERVED. <p>1 = S1_BEARER_ESTABLISH. <p>2 = S1_BEARER_MODIFY. <p>3 = S1_BEARER_RELEASE.  # noqa: E501

        :return: The event_type of this S1BearerSubscription.  # noqa: E501
        :rtype: list[Enum]
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """Sets the event_type of this S1BearerSubscription.

        Description of the subscribed event. The event is included both in the request and in the response. \\nFor the eventType, the following values are currently defined: <p>0 = RESERVED. <p>1 = S1_BEARER_ESTABLISH. <p>2 = S1_BEARER_MODIFY. <p>3 = S1_BEARER_RELEASE.  # noqa: E501

        :param event_type: The event_type of this S1BearerSubscription.  # noqa: E501
        :type: list[Enum]
        """
        if event_type is None:
            raise ValueError("Invalid value for `event_type`, must not be `None`")  # noqa: E501

        self._event_type = event_type

    @property
    def expiry_deadline(self):
        """Gets the expiry_deadline of this S1BearerSubscription.  # noqa: E501


        :return: The expiry_deadline of this S1BearerSubscription.  # noqa: E501
        :rtype: TimeStamp
        """
        return self._expiry_deadline

    @expiry_deadline.setter
    def expiry_deadline(self, expiry_deadline):
        """Sets the expiry_deadline of this S1BearerSubscription.


        :param expiry_deadline: The expiry_deadline of this S1BearerSubscription.  # noqa: E501
        :type: TimeStamp
        """

        self._expiry_deadline = expiry_deadline

    @property
    def subscription_type(self):
        """Gets the subscription_type of this S1BearerSubscription.  # noqa: E501

        Shall be set to \"S1BearerSubscription\".  # noqa: E501

        :return: The subscription_type of this S1BearerSubscription.  # noqa: E501
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type):
        """Sets the subscription_type of this S1BearerSubscription.

        Shall be set to \"S1BearerSubscription\".  # noqa: E501

        :param subscription_type: The subscription_type of this S1BearerSubscription.  # noqa: E501
        :type: str
        """
        if subscription_type is None:
            raise ValueError("Invalid value for `subscription_type`, must not be `None`")  # noqa: E501

        self._subscription_type = subscription_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(S1BearerSubscription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, S1BearerSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
