# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.s1_bearer_subscription_s1_bearer_subscription_criteria import S1BearerSubscriptionS1BearerSubscriptionCriteria  # noqa: E501
from swagger_client.rest import ApiException


class TestS1BearerSubscriptionS1BearerSubscriptionCriteria(unittest.TestCase):
    """S1BearerSubscriptionS1BearerSubscriptionCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS1BearerSubscriptionS1BearerSubscriptionCriteria(self):
        """Test S1BearerSubscriptionS1BearerSubscriptionCriteria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.s1_bearer_subscription_s1_bearer_subscription_criteria.S1BearerSubscriptionS1BearerSubscriptionCriteria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
