# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.s1_bearer_info_s1_bearer_info_detailed import S1BearerInfoS1BearerInfoDetailed  # noqa: E501
from swagger_client.rest import ApiException


class TestS1BearerInfoS1BearerInfoDetailed(unittest.TestCase):
    """S1BearerInfoS1BearerInfoDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS1BearerInfoS1BearerInfoDetailed(self):
        """Test S1BearerInfoS1BearerInfoDetailed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.s1_bearer_info_s1_bearer_info_detailed.S1BearerInfoS1BearerInfoDetailed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
