# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rab_est_notification_erab_qos_parameters import RabEstNotificationErabQosParameters  # noqa: E501
from swagger_client.rest import ApiException


class TestRabEstNotificationErabQosParameters(unittest.TestCase):
    """RabEstNotificationErabQosParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRabEstNotificationErabQosParameters(self):
        """Test RabEstNotificationErabQosParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rab_est_notification_erab_qos_parameters.RabEstNotificationErabQosParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
