# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_inline_subscription import OneOfInlineSubscription  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfInlineSubscription(unittest.TestCase):
    """OneOfInlineSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfInlineSubscription(self):
        """Test OneOfInlineSubscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_inline_subscription.OneOfInlineSubscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
