# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.meas_rep_ue_notification_nr_bn_cs_nr_bn_cell_info import MeasRepUeNotificationNrBNCsNrBNCellInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestMeasRepUeNotificationNrBNCsNrBNCellInfo(unittest.TestCase):
    """MeasRepUeNotificationNrBNCsNrBNCellInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasRepUeNotificationNrBNCsNrBNCellInfo(self):
        """Test MeasRepUeNotificationNrBNCsNrBNCellInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.meas_rep_ue_notification_nr_bn_cs_nr_bn_cell_info.MeasRepUeNotificationNrBNCsNrBNCellInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
