# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cell_change_subscription_filter_criteria_assoc_ho import CellChangeSubscriptionFilterCriteriaAssocHo  # noqa: E501
from swagger_client.rest import ApiException


class TestCellChangeSubscriptionFilterCriteriaAssocHo(unittest.TestCase):
    """CellChangeSubscriptionFilterCriteriaAssocHo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCellChangeSubscriptionFilterCriteriaAssocHo(self):
        """Test CellChangeSubscriptionFilterCriteriaAssocHo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cell_change_subscription_filter_criteria_assoc_ho.CellChangeSubscriptionFilterCriteriaAssocHo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
