# coding: utf-8

"""
    ETSI GS MEC 012 - Radio Network Information API

    The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.  # noqa: E501

    OpenAPI spec version: 2.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rni_api import RniApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRniApi(unittest.TestCase):
    """RniApi unit test stubs"""

    def setUp(self):
        self.api = RniApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_layer2_meas_info_get(self):
        """Test case for layer2_meas_info_get

        Retrieve information on layer 2 measurements  # noqa: E501
        """
        pass

    def test_plmn_info_get(self):
        """Test case for plmn_info_get

        Retrieve information on the underlying Mobile Network that the MEC application is associated to  # noqa: E501
        """
        pass

    def test_rab_info_get(self):
        """Test case for rab_info_get

        Retrieve information on Radio Access Bearers  # noqa: E501
        """
        pass

    def test_s1_bearer_info_get(self):
        """Test case for s1_bearer_info_get

        Retrieve S1-U bearer information related to specific UE(s)  # noqa: E501
        """
        pass

    def test_subscription_link_list_subscriptions_get(self):
        """Test case for subscription_link_list_subscriptions_get

        Retrieve information on subscriptions for notifications  # noqa: E501
        """
        pass

    def test_subscriptions_delete(self):
        """Test case for subscriptions_delete

        Cancel an existing subscription  # noqa: E501
        """
        pass

    def test_subscriptions_get(self):
        """Test case for subscriptions_get

        Retrieve information on current specific subscription  # noqa: E501
        """
        pass

    def test_subscriptions_post(self):
        """Test case for subscriptions_post

        Create a new subscription  # noqa: E501
        """
        pass

    def test_subscriptions_put(self):
        """Test case for subscriptions_put

        Modify an existing subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
